runtime: nodejs20
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  NODE_ENV: 'production'
  PORT: '8080'
  # --- CHANGE: Set the GCP_PROJECT ID ---
  # The secretService will use this to construct the full secret path.
  # Replace 'your-gcp-project-id' with your actual Google Cloud Project ID.
  GCP_PROJECT: 'mindmap-456916'

# The entrypoint tells App Engine how to start your application.
entrypoint: npm start

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 10
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60