runtime: nodejs20
instance_class: F2

env_variables:
  NODE_ENV: 'production'
  # --- CHANGE: Set the GCP_PROJECT ID ---
  # The secretService will use this to construct the full secret path.
  # Replace 'your-gcp-project-id' with your actual Google Cloud Project ID.
  GCP_PROJECT: '977175146736'

# The entrypoint tells App Engine how to start your application.
entrypoint: npm start