runtime: nodejs20
instance_class: F2

env_variables:
  NODE_ENV: 'production'
  # The names here (e.g., GEMINI_API_KEY) MUST match what your code expects (process.env.GEMINI_API_KEY)
  GEMINI_API_KEY: 'projects/977175146736/secrets/GEMINI_API_KEY/versions/latest'
  OPENAI_API_KEY: 'projects/977175146736/secrets/OPENAI_API_KEY/versions/latest'
  DEEPSEEK_API_KEY: 'projects/977175146736/secrets/DEEPSEEK_API_KEY/versions/latest'
  GOOGLE_CLIENT_ID: 'projects/977175146736/secrets/GOOGLE_CLIENT_ID/versions/latest'
  GOOGLE_CLIENT_SECRET: 'projects/977175146736/secrets/GOOGLE_CLIENT_SECRET/versions/latest'
  
# This section gives App Engine permission to access Secret Manager
entrypoint: |-
  npm-run-path exec -- \
  gcloud-secret-env -- \
  npm start