name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        name: Install pnpm
        with:
          version: 12
          runtime: node@26
          cache: true
      - name: Install deps
        run: pnpm i
      - name: Publish to Open VSX Registry
        continue-on-error: true
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OVSX_TOKEN }}
          dependencies: false
      - name: Publish to Visual Studio Marketplace
        continue-on-error: true
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          dependencies: false
          registryUrl: https://marketplace.visualstudio.com
